displayName=Flip Finder Sync
author=osrsflipfinder
description=Auto-sync your Grand Exchange flips, buys & sells to a profit journal
tags=ge,flipping,merch,merchanting,tracker,profit,tax,gp,gold,money,margin,journal
plugins=com.osrsflipfinder.FlipFinderSyncPlugin
build=standard
